#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: Matthew's Blogs
# Short bio or description (displayed in the header)
description: A space to discover and explore the digital humanities.

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Rakefile
  - _scripts/

theme: jekyll-theme-midnight

    <!-- HEADER -->
    <div id="header_wrap" class="outer">
        <header class="inner">
          <a id="forkme_banner" href="{{ site.github.repository_url }}">View on GitHub</a>
          {% if site.github.is_project_page %}
            <a id="forkme_banner" href="{{ site.github.repository_url }}">View on GitHub</a>
          {% endif %}

          <h1 id="project_title">{{ site.title | default: site.github.repository_name }}</h1>
          <h2 id="project_tagline">{{ site.description | default: site.github.project_tagline }}</h2>
